#!/bin/sh
uci set turboacc.config.sw_flow='0'
uci commit turboacc
uci del system.ntp.enabled
uci del system.ntp.enable_server
uci set system.cfg01e48a.zonename='Asia/Shanghai'
uci set system.cfg01e48a.timezone='CST-8'
uci set system.cfg01e48a.log_proto='udp'
uci set system.cfg01e48a.conloglevel='8'
uci set system.cfg01e48a.cronloglevel='5'
uci commit system
echo "0 */1 * * * sync && echo 3 > /proc/sys/vm/drop_caches" >>/etc/crontabs/root
exit 0
